# Copyright © 2023 Axkea, spacewander
# Copyright © 2025 United Security Providers AG, Switzerland
# SPDX-License-Identifier: Apache-2.0
---
services:
  httpbin:
    image: mccutchen/go-httpbin:2.18.1
    environment:
      - MAX_BODY_SIZE=15728640 # 15 MiB
    ports:
      - 8081:8080
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  chown:
    image: alpine:3.16
    command:
      - /bin/sh
      - -c
      - chown -R 101:101 /etc/envoy/logs
    volumes:
      - ./logs:/etc/envoy/logs:rw

  envoy:
    depends_on:
      - chown
      - httpbin
    image: coraza-waf-envoy
    command:
      - -c
      - /etc/envoy/envoy.yaml
      - --log-format [%Y-%m-%d %T.%f][%t][%l][%n] [%g:%#] %v
      - --log-path
      - /etc/envoy/logs/envoy.log
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../build/coraza-waf.so:/etc/envoy/coraza-waf.so
      - ./logs:/etc/envoy/logs:rw
    ports:
      - 10000:10000
      - 9999:9999
    environment:
      - GODEBUG=cgocheck=0
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
